# Generated by Django 3.0.1 on 2020-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddFacultyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(max_length=1000)),
                ('StaffQualification', models.CharField(max_length=5000)),
                ('Subject', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=10000)),
                ('EventDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Body', models.CharField(max_length=10000)),
                ('Images', models.FileField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
