# Generated by Django 3.0.1 on 2020-01-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shs_website', '0002_auto_20200122_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
